// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simple_message.proto

package com.java.flink.stream.proto;

public final class SimpleMessageProtos {
  private SimpleMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimpleMessageJavaTypesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SimpleMessageJavaTypes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string string_value = 2;</code>
     * @return The stringValue.
     */
    String getStringValue();
    /**
     * <code>string string_value = 2;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>int32 int32_value = 3;</code>
     * @return The int32Value.
     */
    int getInt32Value();

    /**
     * <code>int64 int64_value = 4;</code>
     * @return The int64Value.
     */
    long getInt64Value();

    /**
     * <code>double double_value = 5;</code>
     * @return The doubleValue.
     */
    double getDoubleValue();

    /**
     * <code>float float_value = 6;</code>
     * @return The floatValue.
     */
    float getFloatValue();

    /**
     * <code>bool bool_value = 7;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <code>bytes bytes_value = 8;</code>
     * @return The bytesValue.
     */
    com.google.protobuf.ByteString getBytesValue();
  }
  /**
   * Protobuf type {@code SimpleMessageJavaTypes}
   */
  public static final class SimpleMessageJavaTypes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SimpleMessageJavaTypes)
      SimpleMessageJavaTypesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleMessageJavaTypes.newBuilder() to construct.
    private SimpleMessageJavaTypes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleMessageJavaTypes() {
      stringValue_ = "";
      bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleMessageJavaTypes();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SimpleMessageProtos.internal_static_SimpleMessageJavaTypes_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SimpleMessageProtos.internal_static_SimpleMessageJavaTypes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SimpleMessageJavaTypes.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object stringValue_ = "";
    /**
     * <code>string string_value = 2;</code>
     * @return The stringValue.
     */
    @Override
    public String getStringValue() {
      Object ref = stringValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      }
    }
    /**
     * <code>string string_value = 2;</code>
     * @return The bytes for stringValue.
     */
    @Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INT32_VALUE_FIELD_NUMBER = 3;
    private int int32Value_ = 0;
    /**
     * <code>int32 int32_value = 3;</code>
     * @return The int32Value.
     */
    @Override
    public int getInt32Value() {
      return int32Value_;
    }

    public static final int INT64_VALUE_FIELD_NUMBER = 4;
    private long int64Value_ = 0L;
    /**
     * <code>int64 int64_value = 4;</code>
     * @return The int64Value.
     */
    @Override
    public long getInt64Value() {
      return int64Value_;
    }

    public static final int DOUBLE_VALUE_FIELD_NUMBER = 5;
    private double doubleValue_ = 0D;
    /**
     * <code>double double_value = 5;</code>
     * @return The doubleValue.
     */
    @Override
    public double getDoubleValue() {
      return doubleValue_;
    }

    public static final int FLOAT_VALUE_FIELD_NUMBER = 6;
    private float floatValue_ = 0F;
    /**
     * <code>float float_value = 6;</code>
     * @return The floatValue.
     */
    @Override
    public float getFloatValue() {
      return floatValue_;
    }

    public static final int BOOL_VALUE_FIELD_NUMBER = 7;
    private boolean boolValue_ = false;
    /**
     * <code>bool bool_value = 7;</code>
     * @return The boolValue.
     */
    @Override
    public boolean getBoolValue() {
      return boolValue_;
    }

    public static final int BYTES_VALUE_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes_value = 8;</code>
     * @return The bytesValue.
     */
    @Override
    public com.google.protobuf.ByteString getBytesValue() {
      return bytesValue_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stringValue_);
      }
      if (int32Value_ != 0) {
        output.writeInt32(3, int32Value_);
      }
      if (int64Value_ != 0L) {
        output.writeInt64(4, int64Value_);
      }
      if (Double.doubleToRawLongBits(doubleValue_) != 0) {
        output.writeDouble(5, doubleValue_);
      }
      if (Float.floatToRawIntBits(floatValue_) != 0) {
        output.writeFloat(6, floatValue_);
      }
      if (boolValue_ != false) {
        output.writeBool(7, boolValue_);
      }
      if (!bytesValue_.isEmpty()) {
        output.writeBytes(8, bytesValue_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stringValue_);
      }
      if (int32Value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, int32Value_);
      }
      if (int64Value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, int64Value_);
      }
      if (Double.doubleToRawLongBits(doubleValue_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, doubleValue_);
      }
      if (Float.floatToRawIntBits(floatValue_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, floatValue_);
      }
      if (boolValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, boolValue_);
      }
      if (!bytesValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, bytesValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SimpleMessageJavaTypes)) {
        return super.equals(obj);
      }
      SimpleMessageJavaTypes other = (SimpleMessageJavaTypes) obj;

      if (getId()
          != other.getId()) return false;
      if (!getStringValue()
          .equals(other.getStringValue())) return false;
      if (getInt32Value()
          != other.getInt32Value()) return false;
      if (getInt64Value()
          != other.getInt64Value()) return false;
      if (Double.doubleToLongBits(getDoubleValue())
          != Double.doubleToLongBits(
              other.getDoubleValue())) return false;
      if (Float.floatToIntBits(getFloatValue())
          != Float.floatToIntBits(
              other.getFloatValue())) return false;
      if (getBoolValue()
          != other.getBoolValue()) return false;
      if (!getBytesValue()
          .equals(other.getBytesValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue().hashCode();
      hash = (37 * hash) + INT32_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Value();
      hash = (37 * hash) + INT64_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInt64Value());
      hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDoubleValue()));
      hash = (37 * hash) + FLOAT_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getFloatValue());
      hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoolValue());
      hash = (37 * hash) + BYTES_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getBytesValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SimpleMessageJavaTypes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleMessageJavaTypes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleMessageJavaTypes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleMessageJavaTypes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleMessageJavaTypes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleMessageJavaTypes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleMessageJavaTypes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimpleMessageJavaTypes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SimpleMessageJavaTypes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SimpleMessageJavaTypes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SimpleMessageJavaTypes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimpleMessageJavaTypes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SimpleMessageJavaTypes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SimpleMessageJavaTypes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SimpleMessageJavaTypes)
        SimpleMessageJavaTypesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SimpleMessageProtos.internal_static_SimpleMessageJavaTypes_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SimpleMessageProtos.internal_static_SimpleMessageJavaTypes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SimpleMessageJavaTypes.class, Builder.class);
      }

      // Construct using com.java.flink.stream.proto.SimpleMessageProtos.SimpleMessageJavaTypes.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        stringValue_ = "";
        int32Value_ = 0;
        int64Value_ = 0L;
        doubleValue_ = 0D;
        floatValue_ = 0F;
        boolValue_ = false;
        bytesValue_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SimpleMessageProtos.internal_static_SimpleMessageJavaTypes_descriptor;
      }

      @Override
      public SimpleMessageJavaTypes getDefaultInstanceForType() {
        return SimpleMessageJavaTypes.getDefaultInstance();
      }

      @Override
      public SimpleMessageJavaTypes build() {
        SimpleMessageJavaTypes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SimpleMessageJavaTypes buildPartial() {
        SimpleMessageJavaTypes result = new SimpleMessageJavaTypes(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SimpleMessageJavaTypes result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stringValue_ = stringValue_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.int32Value_ = int32Value_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.int64Value_ = int64Value_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.doubleValue_ = doubleValue_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.floatValue_ = floatValue_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.boolValue_ = boolValue_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.bytesValue_ = bytesValue_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SimpleMessageJavaTypes) {
          return mergeFrom((SimpleMessageJavaTypes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SimpleMessageJavaTypes other) {
        if (other == SimpleMessageJavaTypes.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getStringValue().isEmpty()) {
          stringValue_ = other.stringValue_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getInt32Value() != 0) {
          setInt32Value(other.getInt32Value());
        }
        if (other.getInt64Value() != 0L) {
          setInt64Value(other.getInt64Value());
        }
        if (other.getDoubleValue() != 0D) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.getFloatValue() != 0F) {
          setFloatValue(other.getFloatValue());
        }
        if (other.getBoolValue() != false) {
          setBoolValue(other.getBoolValue());
        }
        if (other.getBytesValue() != com.google.protobuf.ByteString.EMPTY) {
          setBytesValue(other.getBytesValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                stringValue_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int32Value_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                int64Value_ = input.readInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 41: {
                doubleValue_ = input.readDouble();
                bitField0_ |= 0x00000010;
                break;
              } // case 41
              case 53: {
                floatValue_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 56: {
                boolValue_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                bytesValue_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object stringValue_ = "";
      /**
       * <code>string string_value = 2;</code>
       * @return The stringValue.
       */
      public String getStringValue() {
        Object ref = stringValue_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string string_value = 2;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string_value = 2;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        stringValue_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string string_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        stringValue_ = getDefaultInstance().getStringValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string string_value = 2;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stringValue_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int int32Value_ ;
      /**
       * <code>int32 int32_value = 3;</code>
       * @return The int32Value.
       */
      @Override
      public int getInt32Value() {
        return int32Value_;
      }
      /**
       * <code>int32 int32_value = 3;</code>
       * @param value The int32Value to set.
       * @return This builder for chaining.
       */
      public Builder setInt32Value(int value) {

        int32Value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int32_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt32Value() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int32Value_ = 0;
        onChanged();
        return this;
      }

      private long int64Value_ ;
      /**
       * <code>int64 int64_value = 4;</code>
       * @return The int64Value.
       */
      @Override
      public long getInt64Value() {
        return int64Value_;
      }
      /**
       * <code>int64 int64_value = 4;</code>
       * @param value The int64Value to set.
       * @return This builder for chaining.
       */
      public Builder setInt64Value(long value) {

        int64Value_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int64 int64_value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt64Value() {
        bitField0_ = (bitField0_ & ~0x00000008);
        int64Value_ = 0L;
        onChanged();
        return this;
      }

      private double doubleValue_ ;
      /**
       * <code>double double_value = 5;</code>
       * @return The doubleValue.
       */
      @Override
      public double getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <code>double double_value = 5;</code>
       * @param value The doubleValue to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleValue(double value) {

        doubleValue_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>double double_value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }

      private float floatValue_ ;
      /**
       * <code>float float_value = 6;</code>
       * @return The floatValue.
       */
      @Override
      public float getFloatValue() {
        return floatValue_;
      }
      /**
       * <code>float float_value = 6;</code>
       * @param value The floatValue to set.
       * @return This builder for chaining.
       */
      public Builder setFloatValue(float value) {

        floatValue_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>float float_value = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        floatValue_ = 0F;
        onChanged();
        return this;
      }

      private boolean boolValue_ ;
      /**
       * <code>bool bool_value = 7;</code>
       * @return The boolValue.
       */
      @Override
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <code>bool bool_value = 7;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {

        boolValue_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>bool bool_value = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        bitField0_ = (bitField0_ & ~0x00000040);
        boolValue_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes_value = 8;</code>
       * @return The bytesValue.
       */
      @Override
      public com.google.protobuf.ByteString getBytesValue() {
        return bytesValue_;
      }
      /**
       * <code>bytes bytes_value = 8;</code>
       * @param value The bytesValue to set.
       * @return This builder for chaining.
       */
      public Builder setBytesValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        bytesValue_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes_value = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytesValue() {
        bitField0_ = (bitField0_ & ~0x00000080);
        bytesValue_ = getDefaultInstance().getBytesValue();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SimpleMessageJavaTypes)
    }

    // @@protoc_insertion_point(class_scope:SimpleMessageJavaTypes)
    private static final SimpleMessageJavaTypes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SimpleMessageJavaTypes();
    }

    public static SimpleMessageJavaTypes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleMessageJavaTypes>
        PARSER = new com.google.protobuf.AbstractParser<SimpleMessageJavaTypes>() {
      @Override
      public SimpleMessageJavaTypes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SimpleMessageJavaTypes> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SimpleMessageJavaTypes> getParserForType() {
      return PARSER;
    }

    @Override
    public SimpleMessageJavaTypes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimpleMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SimpleMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string string_value = 2;</code>
     * @return The stringValue.
     */
    String getStringValue();
    /**
     * <code>string string_value = 2;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>int32 int32_value = 3;</code>
     * @return The int32Value.
     */
    int getInt32Value();

    /**
     * <code>uint32 uint32_value = 4;</code>
     * @return The uint32Value.
     */
    int getUint32Value();

    /**
     * <code>sint32 sint32_value = 5;</code>
     * @return The sint32Value.
     */
    int getSint32Value();

    /**
     * <code>fixed32 fixed32_value = 6;</code>
     * @return The fixed32Value.
     */
    int getFixed32Value();

    /**
     * <code>sfixed32 sfixed32_value = 7;</code>
     * @return The sfixed32Value.
     */
    int getSfixed32Value();

    /**
     * <code>int64 int64_value = 8;</code>
     * @return The int64Value.
     */
    long getInt64Value();

    /**
     * <code>uint64 uint64_value = 9;</code>
     * @return The uint64Value.
     */
    long getUint64Value();

    /**
     * <code>sint64 sint64_value = 10;</code>
     * @return The sint64Value.
     */
    long getSint64Value();

    /**
     * <code>fixed64 fixed64_value = 11;</code>
     * @return The fixed64Value.
     */
    long getFixed64Value();

    /**
     * <code>sfixed64 sfixed64_value = 12;</code>
     * @return The sfixed64Value.
     */
    long getSfixed64Value();

    /**
     * <code>double double_value = 13;</code>
     * @return The doubleValue.
     */
    double getDoubleValue();

    /**
     * <code>float float_value = 14;</code>
     * @return The floatValue.
     */
    float getFloatValue();

    /**
     * <code>bool bool_value = 15;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <code>bytes bytes_value = 16;</code>
     * @return The bytesValue.
     */
    com.google.protobuf.ByteString getBytesValue();
  }
  /**
   * Protobuf type {@code SimpleMessage}
   */
  public static final class SimpleMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SimpleMessage)
      SimpleMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleMessage.newBuilder() to construct.
    private SimpleMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleMessage() {
      stringValue_ = "";
      bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SimpleMessageProtos.internal_static_SimpleMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SimpleMessageProtos.internal_static_SimpleMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SimpleMessage.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_ = 0L;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object stringValue_ = "";
    /**
     * <code>string string_value = 2;</code>
     * @return The stringValue.
     */
    @Override
    public String getStringValue() {
      Object ref = stringValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        stringValue_ = s;
        return s;
      }
    }
    /**
     * <code>string string_value = 2;</code>
     * @return The bytes for stringValue.
     */
    @Override
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      Object ref = stringValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        stringValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INT32_VALUE_FIELD_NUMBER = 3;
    private int int32Value_ = 0;
    /**
     * <code>int32 int32_value = 3;</code>
     * @return The int32Value.
     */
    @Override
    public int getInt32Value() {
      return int32Value_;
    }

    public static final int UINT32_VALUE_FIELD_NUMBER = 4;
    private int uint32Value_ = 0;
    /**
     * <code>uint32 uint32_value = 4;</code>
     * @return The uint32Value.
     */
    @Override
    public int getUint32Value() {
      return uint32Value_;
    }

    public static final int SINT32_VALUE_FIELD_NUMBER = 5;
    private int sint32Value_ = 0;
    /**
     * <code>sint32 sint32_value = 5;</code>
     * @return The sint32Value.
     */
    @Override
    public int getSint32Value() {
      return sint32Value_;
    }

    public static final int FIXED32_VALUE_FIELD_NUMBER = 6;
    private int fixed32Value_ = 0;
    /**
     * <code>fixed32 fixed32_value = 6;</code>
     * @return The fixed32Value.
     */
    @Override
    public int getFixed32Value() {
      return fixed32Value_;
    }

    public static final int SFIXED32_VALUE_FIELD_NUMBER = 7;
    private int sfixed32Value_ = 0;
    /**
     * <code>sfixed32 sfixed32_value = 7;</code>
     * @return The sfixed32Value.
     */
    @Override
    public int getSfixed32Value() {
      return sfixed32Value_;
    }

    public static final int INT64_VALUE_FIELD_NUMBER = 8;
    private long int64Value_ = 0L;
    /**
     * <code>int64 int64_value = 8;</code>
     * @return The int64Value.
     */
    @Override
    public long getInt64Value() {
      return int64Value_;
    }

    public static final int UINT64_VALUE_FIELD_NUMBER = 9;
    private long uint64Value_ = 0L;
    /**
     * <code>uint64 uint64_value = 9;</code>
     * @return The uint64Value.
     */
    @Override
    public long getUint64Value() {
      return uint64Value_;
    }

    public static final int SINT64_VALUE_FIELD_NUMBER = 10;
    private long sint64Value_ = 0L;
    /**
     * <code>sint64 sint64_value = 10;</code>
     * @return The sint64Value.
     */
    @Override
    public long getSint64Value() {
      return sint64Value_;
    }

    public static final int FIXED64_VALUE_FIELD_NUMBER = 11;
    private long fixed64Value_ = 0L;
    /**
     * <code>fixed64 fixed64_value = 11;</code>
     * @return The fixed64Value.
     */
    @Override
    public long getFixed64Value() {
      return fixed64Value_;
    }

    public static final int SFIXED64_VALUE_FIELD_NUMBER = 12;
    private long sfixed64Value_ = 0L;
    /**
     * <code>sfixed64 sfixed64_value = 12;</code>
     * @return The sfixed64Value.
     */
    @Override
    public long getSfixed64Value() {
      return sfixed64Value_;
    }

    public static final int DOUBLE_VALUE_FIELD_NUMBER = 13;
    private double doubleValue_ = 0D;
    /**
     * <code>double double_value = 13;</code>
     * @return The doubleValue.
     */
    @Override
    public double getDoubleValue() {
      return doubleValue_;
    }

    public static final int FLOAT_VALUE_FIELD_NUMBER = 14;
    private float floatValue_ = 0F;
    /**
     * <code>float float_value = 14;</code>
     * @return The floatValue.
     */
    @Override
    public float getFloatValue() {
      return floatValue_;
    }

    public static final int BOOL_VALUE_FIELD_NUMBER = 15;
    private boolean boolValue_ = false;
    /**
     * <code>bool bool_value = 15;</code>
     * @return The boolValue.
     */
    @Override
    public boolean getBoolValue() {
      return boolValue_;
    }

    public static final int BYTES_VALUE_FIELD_NUMBER = 16;
    private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes bytes_value = 16;</code>
     * @return The bytesValue.
     */
    @Override
    public com.google.protobuf.ByteString getBytesValue() {
      return bytesValue_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, stringValue_);
      }
      if (int32Value_ != 0) {
        output.writeInt32(3, int32Value_);
      }
      if (uint32Value_ != 0) {
        output.writeUInt32(4, uint32Value_);
      }
      if (sint32Value_ != 0) {
        output.writeSInt32(5, sint32Value_);
      }
      if (fixed32Value_ != 0) {
        output.writeFixed32(6, fixed32Value_);
      }
      if (sfixed32Value_ != 0) {
        output.writeSFixed32(7, sfixed32Value_);
      }
      if (int64Value_ != 0L) {
        output.writeInt64(8, int64Value_);
      }
      if (uint64Value_ != 0L) {
        output.writeUInt64(9, uint64Value_);
      }
      if (sint64Value_ != 0L) {
        output.writeSInt64(10, sint64Value_);
      }
      if (fixed64Value_ != 0L) {
        output.writeFixed64(11, fixed64Value_);
      }
      if (sfixed64Value_ != 0L) {
        output.writeSFixed64(12, sfixed64Value_);
      }
      if (Double.doubleToRawLongBits(doubleValue_) != 0) {
        output.writeDouble(13, doubleValue_);
      }
      if (Float.floatToRawIntBits(floatValue_) != 0) {
        output.writeFloat(14, floatValue_);
      }
      if (boolValue_ != false) {
        output.writeBool(15, boolValue_);
      }
      if (!bytesValue_.isEmpty()) {
        output.writeBytes(16, bytesValue_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(stringValue_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, stringValue_);
      }
      if (int32Value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, int32Value_);
      }
      if (uint32Value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, uint32Value_);
      }
      if (sint32Value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, sint32Value_);
      }
      if (fixed32Value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(6, fixed32Value_);
      }
      if (sfixed32Value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed32Size(7, sfixed32Value_);
      }
      if (int64Value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, int64Value_);
      }
      if (uint64Value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(9, uint64Value_);
      }
      if (sint64Value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(10, sint64Value_);
      }
      if (fixed64Value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(11, fixed64Value_);
      }
      if (sfixed64Value_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeSFixed64Size(12, sfixed64Value_);
      }
      if (Double.doubleToRawLongBits(doubleValue_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(13, doubleValue_);
      }
      if (Float.floatToRawIntBits(floatValue_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(14, floatValue_);
      }
      if (boolValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, boolValue_);
      }
      if (!bytesValue_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, bytesValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SimpleMessage)) {
        return super.equals(obj);
      }
      SimpleMessage other = (SimpleMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getStringValue()
          .equals(other.getStringValue())) return false;
      if (getInt32Value()
          != other.getInt32Value()) return false;
      if (getUint32Value()
          != other.getUint32Value()) return false;
      if (getSint32Value()
          != other.getSint32Value()) return false;
      if (getFixed32Value()
          != other.getFixed32Value()) return false;
      if (getSfixed32Value()
          != other.getSfixed32Value()) return false;
      if (getInt64Value()
          != other.getInt64Value()) return false;
      if (getUint64Value()
          != other.getUint64Value()) return false;
      if (getSint64Value()
          != other.getSint64Value()) return false;
      if (getFixed64Value()
          != other.getFixed64Value()) return false;
      if (getSfixed64Value()
          != other.getSfixed64Value()) return false;
      if (Double.doubleToLongBits(getDoubleValue())
          != Double.doubleToLongBits(
              other.getDoubleValue())) return false;
      if (Float.floatToIntBits(getFloatValue())
          != Float.floatToIntBits(
              other.getFloatValue())) return false;
      if (getBoolValue()
          != other.getBoolValue()) return false;
      if (!getBytesValue()
          .equals(other.getBytesValue())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getStringValue().hashCode();
      hash = (37 * hash) + INT32_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getInt32Value();
      hash = (37 * hash) + UINT32_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getUint32Value();
      hash = (37 * hash) + SINT32_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getSint32Value();
      hash = (37 * hash) + FIXED32_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getFixed32Value();
      hash = (37 * hash) + SFIXED32_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getSfixed32Value();
      hash = (37 * hash) + INT64_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getInt64Value());
      hash = (37 * hash) + UINT64_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUint64Value());
      hash = (37 * hash) + SINT64_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSint64Value());
      hash = (37 * hash) + FIXED64_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFixed64Value());
      hash = (37 * hash) + SFIXED64_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSfixed64Value());
      hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDoubleValue()));
      hash = (37 * hash) + FLOAT_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getFloatValue());
      hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBoolValue());
      hash = (37 * hash) + BYTES_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getBytesValue().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SimpleMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SimpleMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SimpleMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimpleMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SimpleMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SimpleMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SimpleMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SimpleMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SimpleMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SimpleMessage)
        SimpleMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SimpleMessageProtos.internal_static_SimpleMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SimpleMessageProtos.internal_static_SimpleMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SimpleMessage.class, Builder.class);
      }

      // Construct using com.java.flink.stream.proto.SimpleMessageProtos.SimpleMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0L;
        stringValue_ = "";
        int32Value_ = 0;
        uint32Value_ = 0;
        sint32Value_ = 0;
        fixed32Value_ = 0;
        sfixed32Value_ = 0;
        int64Value_ = 0L;
        uint64Value_ = 0L;
        sint64Value_ = 0L;
        fixed64Value_ = 0L;
        sfixed64Value_ = 0L;
        doubleValue_ = 0D;
        floatValue_ = 0F;
        boolValue_ = false;
        bytesValue_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SimpleMessageProtos.internal_static_SimpleMessage_descriptor;
      }

      @Override
      public SimpleMessage getDefaultInstanceForType() {
        return SimpleMessage.getDefaultInstance();
      }

      @Override
      public SimpleMessage build() {
        SimpleMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SimpleMessage buildPartial() {
        SimpleMessage result = new SimpleMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SimpleMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stringValue_ = stringValue_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.int32Value_ = int32Value_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.uint32Value_ = uint32Value_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.sint32Value_ = sint32Value_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.fixed32Value_ = fixed32Value_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.sfixed32Value_ = sfixed32Value_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.int64Value_ = int64Value_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.uint64Value_ = uint64Value_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.sint64Value_ = sint64Value_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.fixed64Value_ = fixed64Value_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.sfixed64Value_ = sfixed64Value_;
        }
        if (((from_bitField0_ & 0x00001000) != 0)) {
          result.doubleValue_ = doubleValue_;
        }
        if (((from_bitField0_ & 0x00002000) != 0)) {
          result.floatValue_ = floatValue_;
        }
        if (((from_bitField0_ & 0x00004000) != 0)) {
          result.boolValue_ = boolValue_;
        }
        if (((from_bitField0_ & 0x00008000) != 0)) {
          result.bytesValue_ = bytesValue_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SimpleMessage) {
          return mergeFrom((SimpleMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SimpleMessage other) {
        if (other == SimpleMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getStringValue().isEmpty()) {
          stringValue_ = other.stringValue_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getInt32Value() != 0) {
          setInt32Value(other.getInt32Value());
        }
        if (other.getUint32Value() != 0) {
          setUint32Value(other.getUint32Value());
        }
        if (other.getSint32Value() != 0) {
          setSint32Value(other.getSint32Value());
        }
        if (other.getFixed32Value() != 0) {
          setFixed32Value(other.getFixed32Value());
        }
        if (other.getSfixed32Value() != 0) {
          setSfixed32Value(other.getSfixed32Value());
        }
        if (other.getInt64Value() != 0L) {
          setInt64Value(other.getInt64Value());
        }
        if (other.getUint64Value() != 0L) {
          setUint64Value(other.getUint64Value());
        }
        if (other.getSint64Value() != 0L) {
          setSint64Value(other.getSint64Value());
        }
        if (other.getFixed64Value() != 0L) {
          setFixed64Value(other.getFixed64Value());
        }
        if (other.getSfixed64Value() != 0L) {
          setSfixed64Value(other.getSfixed64Value());
        }
        if (other.getDoubleValue() != 0D) {
          setDoubleValue(other.getDoubleValue());
        }
        if (other.getFloatValue() != 0F) {
          setFloatValue(other.getFloatValue());
        }
        if (other.getBoolValue() != false) {
          setBoolValue(other.getBoolValue());
        }
        if (other.getBytesValue() != com.google.protobuf.ByteString.EMPTY) {
          setBytesValue(other.getBytesValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                stringValue_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                int32Value_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                uint32Value_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                sint32Value_ = input.readSInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 53: {
                fixed32Value_ = input.readFixed32();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 61: {
                sfixed32Value_ = input.readSFixed32();
                bitField0_ |= 0x00000040;
                break;
              } // case 61
              case 64: {
                int64Value_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                uint64Value_ = input.readUInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 80: {
                sint64Value_ = input.readSInt64();
                bitField0_ |= 0x00000200;
                break;
              } // case 80
              case 89: {
                fixed64Value_ = input.readFixed64();
                bitField0_ |= 0x00000400;
                break;
              } // case 89
              case 97: {
                sfixed64Value_ = input.readSFixed64();
                bitField0_ |= 0x00000800;
                break;
              } // case 97
              case 105: {
                doubleValue_ = input.readDouble();
                bitField0_ |= 0x00001000;
                break;
              } // case 105
              case 117: {
                floatValue_ = input.readFloat();
                bitField0_ |= 0x00002000;
                break;
              } // case 117
              case 120: {
                boolValue_ = input.readBool();
                bitField0_ |= 0x00004000;
                break;
              } // case 120
              case 130: {
                bytesValue_ = input.readBytes();
                bitField0_ |= 0x00008000;
                break;
              } // case 130
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private Object stringValue_ = "";
      /**
       * <code>string string_value = 2;</code>
       * @return The stringValue.
       */
      public String getStringValue() {
        Object ref = stringValue_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          stringValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string string_value = 2;</code>
       * @return The bytes for stringValue.
       */
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        Object ref = stringValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          stringValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string_value = 2;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        stringValue_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string string_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        stringValue_ = getDefaultInstance().getStringValue();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string string_value = 2;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        stringValue_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int int32Value_ ;
      /**
       * <code>int32 int32_value = 3;</code>
       * @return The int32Value.
       */
      @Override
      public int getInt32Value() {
        return int32Value_;
      }
      /**
       * <code>int32 int32_value = 3;</code>
       * @param value The int32Value to set.
       * @return This builder for chaining.
       */
      public Builder setInt32Value(int value) {

        int32Value_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int32_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt32Value() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int32Value_ = 0;
        onChanged();
        return this;
      }

      private int uint32Value_ ;
      /**
       * <code>uint32 uint32_value = 4;</code>
       * @return The uint32Value.
       */
      @Override
      public int getUint32Value() {
        return uint32Value_;
      }
      /**
       * <code>uint32 uint32_value = 4;</code>
       * @param value The uint32Value to set.
       * @return This builder for chaining.
       */
      public Builder setUint32Value(int value) {

        uint32Value_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uint32_value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUint32Value() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uint32Value_ = 0;
        onChanged();
        return this;
      }

      private int sint32Value_ ;
      /**
       * <code>sint32 sint32_value = 5;</code>
       * @return The sint32Value.
       */
      @Override
      public int getSint32Value() {
        return sint32Value_;
      }
      /**
       * <code>sint32 sint32_value = 5;</code>
       * @param value The sint32Value to set.
       * @return This builder for chaining.
       */
      public Builder setSint32Value(int value) {

        sint32Value_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 sint32_value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSint32Value() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sint32Value_ = 0;
        onChanged();
        return this;
      }

      private int fixed32Value_ ;
      /**
       * <code>fixed32 fixed32_value = 6;</code>
       * @return The fixed32Value.
       */
      @Override
      public int getFixed32Value() {
        return fixed32Value_;
      }
      /**
       * <code>fixed32 fixed32_value = 6;</code>
       * @param value The fixed32Value to set.
       * @return This builder for chaining.
       */
      public Builder setFixed32Value(int value) {

        fixed32Value_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 fixed32_value = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFixed32Value() {
        bitField0_ = (bitField0_ & ~0x00000020);
        fixed32Value_ = 0;
        onChanged();
        return this;
      }

      private int sfixed32Value_ ;
      /**
       * <code>sfixed32 sfixed32_value = 7;</code>
       * @return The sfixed32Value.
       */
      @Override
      public int getSfixed32Value() {
        return sfixed32Value_;
      }
      /**
       * <code>sfixed32 sfixed32_value = 7;</code>
       * @param value The sfixed32Value to set.
       * @return This builder for chaining.
       */
      public Builder setSfixed32Value(int value) {

        sfixed32Value_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed32 sfixed32_value = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSfixed32Value() {
        bitField0_ = (bitField0_ & ~0x00000040);
        sfixed32Value_ = 0;
        onChanged();
        return this;
      }

      private long int64Value_ ;
      /**
       * <code>int64 int64_value = 8;</code>
       * @return The int64Value.
       */
      @Override
      public long getInt64Value() {
        return int64Value_;
      }
      /**
       * <code>int64 int64_value = 8;</code>
       * @param value The int64Value to set.
       * @return This builder for chaining.
       */
      public Builder setInt64Value(long value) {

        int64Value_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 int64_value = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearInt64Value() {
        bitField0_ = (bitField0_ & ~0x00000080);
        int64Value_ = 0L;
        onChanged();
        return this;
      }

      private long uint64Value_ ;
      /**
       * <code>uint64 uint64_value = 9;</code>
       * @return The uint64Value.
       */
      @Override
      public long getUint64Value() {
        return uint64Value_;
      }
      /**
       * <code>uint64 uint64_value = 9;</code>
       * @param value The uint64Value to set.
       * @return This builder for chaining.
       */
      public Builder setUint64Value(long value) {

        uint64Value_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 uint64_value = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUint64Value() {
        bitField0_ = (bitField0_ & ~0x00000100);
        uint64Value_ = 0L;
        onChanged();
        return this;
      }

      private long sint64Value_ ;
      /**
       * <code>sint64 sint64_value = 10;</code>
       * @return The sint64Value.
       */
      @Override
      public long getSint64Value() {
        return sint64Value_;
      }
      /**
       * <code>sint64 sint64_value = 10;</code>
       * @param value The sint64Value to set.
       * @return This builder for chaining.
       */
      public Builder setSint64Value(long value) {

        sint64Value_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>sint64 sint64_value = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSint64Value() {
        bitField0_ = (bitField0_ & ~0x00000200);
        sint64Value_ = 0L;
        onChanged();
        return this;
      }

      private long fixed64Value_ ;
      /**
       * <code>fixed64 fixed64_value = 11;</code>
       * @return The fixed64Value.
       */
      @Override
      public long getFixed64Value() {
        return fixed64Value_;
      }
      /**
       * <code>fixed64 fixed64_value = 11;</code>
       * @param value The fixed64Value to set.
       * @return This builder for chaining.
       */
      public Builder setFixed64Value(long value) {

        fixed64Value_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>fixed64 fixed64_value = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearFixed64Value() {
        bitField0_ = (bitField0_ & ~0x00000400);
        fixed64Value_ = 0L;
        onChanged();
        return this;
      }

      private long sfixed64Value_ ;
      /**
       * <code>sfixed64 sfixed64_value = 12;</code>
       * @return The sfixed64Value.
       */
      @Override
      public long getSfixed64Value() {
        return sfixed64Value_;
      }
      /**
       * <code>sfixed64 sfixed64_value = 12;</code>
       * @param value The sfixed64Value to set.
       * @return This builder for chaining.
       */
      public Builder setSfixed64Value(long value) {

        sfixed64Value_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>sfixed64 sfixed64_value = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearSfixed64Value() {
        bitField0_ = (bitField0_ & ~0x00000800);
        sfixed64Value_ = 0L;
        onChanged();
        return this;
      }

      private double doubleValue_ ;
      /**
       * <code>double double_value = 13;</code>
       * @return The doubleValue.
       */
      @Override
      public double getDoubleValue() {
        return doubleValue_;
      }
      /**
       * <code>double double_value = 13;</code>
       * @param value The doubleValue to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleValue(double value) {

        doubleValue_ = value;
        bitField0_ |= 0x00001000;
        onChanged();
        return this;
      }
      /**
       * <code>double double_value = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleValue() {
        bitField0_ = (bitField0_ & ~0x00001000);
        doubleValue_ = 0D;
        onChanged();
        return this;
      }

      private float floatValue_ ;
      /**
       * <code>float float_value = 14;</code>
       * @return The floatValue.
       */
      @Override
      public float getFloatValue() {
        return floatValue_;
      }
      /**
       * <code>float float_value = 14;</code>
       * @param value The floatValue to set.
       * @return This builder for chaining.
       */
      public Builder setFloatValue(float value) {

        floatValue_ = value;
        bitField0_ |= 0x00002000;
        onChanged();
        return this;
      }
      /**
       * <code>float float_value = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearFloatValue() {
        bitField0_ = (bitField0_ & ~0x00002000);
        floatValue_ = 0F;
        onChanged();
        return this;
      }

      private boolean boolValue_ ;
      /**
       * <code>bool bool_value = 15;</code>
       * @return The boolValue.
       */
      @Override
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <code>bool bool_value = 15;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {

        boolValue_ = value;
        bitField0_ |= 0x00004000;
        onChanged();
        return this;
      }
      /**
       * <code>bool bool_value = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        bitField0_ = (bitField0_ & ~0x00004000);
        boolValue_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString bytesValue_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes bytes_value = 16;</code>
       * @return The bytesValue.
       */
      @Override
      public com.google.protobuf.ByteString getBytesValue() {
        return bytesValue_;
      }
      /**
       * <code>bytes bytes_value = 16;</code>
       * @param value The bytesValue to set.
       * @return This builder for chaining.
       */
      public Builder setBytesValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        bytesValue_ = value;
        bitField0_ |= 0x00008000;
        onChanged();
        return this;
      }
      /**
       * <code>bytes bytes_value = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearBytesValue() {
        bitField0_ = (bitField0_ & ~0x00008000);
        bytesValue_ = getDefaultInstance().getBytesValue();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SimpleMessage)
    }

    // @@protoc_insertion_point(class_scope:SimpleMessage)
    private static final SimpleMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SimpleMessage();
    }

    public static SimpleMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleMessage>
        PARSER = new com.google.protobuf.AbstractParser<SimpleMessage>() {
      @Override
      public SimpleMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SimpleMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SimpleMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public SimpleMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleMessageJavaTypes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleMessageJavaTypes_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024simple_message.proto\"\270\001\n\026SimpleMessage" +
      "JavaTypes\022\n\n\002id\030\001 \001(\003\022\024\n\014string_value\030\002 " +
      "\001(\t\022\023\n\013int32_value\030\003 \001(\005\022\023\n\013int64_value\030" +
      "\004 \001(\003\022\024\n\014double_value\030\005 \001(\001\022\023\n\013float_val" +
      "ue\030\006 \001(\002\022\022\n\nbool_value\030\007 \001(\010\022\023\n\013bytes_va" +
      "lue\030\010 \001(\014\"\345\002\n\rSimpleMessage\022\n\n\002id\030\001 \001(\003\022" +
      "\024\n\014string_value\030\002 \001(\t\022\023\n\013int32_value\030\003 \001" +
      "(\005\022\024\n\014uint32_value\030\004 \001(\r\022\024\n\014sint32_value" +
      "\030\005 \001(\021\022\025\n\rfixed32_value\030\006 \001(\007\022\026\n\016sfixed3" +
      "2_value\030\007 \001(\017\022\023\n\013int64_value\030\010 \001(\003\022\024\n\014ui" +
      "nt64_value\030\t \001(\004\022\024\n\014sint64_value\030\n \001(\022\022\025" +
      "\n\rfixed64_value\030\013 \001(\006\022\026\n\016sfixed64_value\030" +
      "\014 \001(\020\022\024\n\014double_value\030\r \001(\001\022\023\n\013float_val" +
      "ue\030\016 \001(\002\022\022\n\nbool_value\030\017 \001(\010\022\023\n\013bytes_va" +
      "lue\030\020 \001(\014B2\n\033com.java.flink.stream.proto" +
      "B\023SimpleMessageProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SimpleMessageJavaTypes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SimpleMessageJavaTypes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleMessageJavaTypes_descriptor,
        new String[] { "Id", "StringValue", "Int32Value", "Int64Value", "DoubleValue", "FloatValue", "BoolValue", "BytesValue", });
    internal_static_SimpleMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SimpleMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleMessage_descriptor,
        new String[] { "Id", "StringValue", "Int32Value", "Uint32Value", "Sint32Value", "Fixed32Value", "Sfixed32Value", "Int64Value", "Uint64Value", "Sint64Value", "Fixed64Value", "Sfixed64Value", "DoubleValue", "FloatValue", "BoolValue", "BytesValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
